name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1

    - name: Cache NuGet packages
      uses: actions/cache@v3
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
        restore-keys: |
          ${{ runner.os }}-nuget-

    - name: Restore NuGet packages
      run: nuget restore -verbosity detailed

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v2

    - name: Restore dependencies
      run: msbuild /t:Restore

    - name: Build app for release
      run: msbuild /t:rebuild /verbosity:minimal /property:Configuration=Release

    - name: Build Visual Studio Installer project
      run: '"C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\IDE\devenv.com" FenixInstall\FenixInstall.vdproj /Build "Release|Any CPU"'

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Fenix-Modbus
        path: D:\a\Fenix-Modbus\Fenix-Modbus\FenixManager\bin\Release\

    - name: Upload installer artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Fenix-Modbus-Installer
        path: D:\a\Fenix-Modbus\Fenix-Modbus\FenixInstall\bin\Release\
