# This workflow will build a .NET project using MSBuild
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1

    - name: Restore NuGet packages
      run: nuget restore -verbosity detailed

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v2

    - name: Restore dependencies
      run: msbuild /t:Restore

    - name: Build app for release
      run: msbuild -t:rebuild -verbosity:minimal -property:Configuration=Release
