name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1

    - name: Cache NuGet packages
      uses: actions/cache@v3
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
        restore-keys: |
          ${{ runner.os }}-nuget-

    - name: Restore NuGet packages
      run: nuget restore -verbosity detailed

    - name: Set up .NET Framework 4.8 Developer Pack
      run: choco install netfx-4.8-devpack

    - name: Install Visual Studio 2022 Build Tools
      run: choco install visualstudio2022buildtools --package-parameters "--add Microsoft.VisualStudio.Workload.ManagedDesktopBuildTools --includeRecommended --includeOptional"

    - name: Disable Out of Proc Build
      run: |
        "C:\Program Files (x86)\Microsoft Visual Studio\Common7\IDE\CommonExtensions\Microsoft\VSI\DisableOutOfProcBuild\DisableOutOfProcBuild.exe"

    - name: Locate devenv.com
      id: locate-devenv
      run: |
        $vsPath = &"C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe" -latest -products * -requires Microsoft.VisualStudio.Component.VC.Tools.x86.x64 -find **\devenv.com
        echo "::set-output name=devenv-path::$vsPath"

    - name: Build Visual Studio Installer project
      run: |
        $devenvPath="${{ steps.locate-devenv.outputs.devenv-path }}"
        &"$devenvPath" "FenixInstall\FenixInstall.vdproj" /Build "Release|Any CPU"

    - name: Upload installer artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Fenix-Modbus-Installer
        path: D:\a\Fenix-Modbus\Fenix-Modbus\FenixInstall\bin\Release\
