# This workflow will build a .NET project using MSBuild
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1
    - name: Restore NuGet packages
      run: nuget restore
    - name: Find MSBuild
      id: msbuild
      run: |
        echo "::set-output name=path::$(vswhere -latest -products * -requires Microsoft.Component.MSBuild -find MSBuild\**\Bin\MSBuild.exe)"
    - name: Restore dependencies
      run: |
        $msbuild = "${{ steps.msbuild.outputs.path }}"
        & "$msbuild" /t:Restore
    - name: Build
      run: |
        $msbuild = "${{ steps.msbuild.outputs.path }}"
        & "$msbuild" -p:Configuration=Release
